### ISSUE TITLE
Area cut of paris 12th district not right

### ISSUE THREAD

**Issue by websan** [neveldo/mapael-maps#24]
Here is the right cut of it
"district-75112" : "m 676.86371,295.93344 -33.28182,-3.33281 -14.71313,-2.03681 -47.78523,-8.96187 -13.93201,-0.67891 -18.48905,-4.75253 -6.90088,-1.22205 -18.09853,-9.23344 -9.37469,-6.24614 -0.84379,0.0428 0.73648,6.04895 -1.74423,5.03828 -9.95625,28.61504 -2.53693,7.50813 21.26532,25.92914 17.51099,21.09681 15.42665,21.42906 20.8997,26.81607 10.1474,8.71519 13.00251,-10.90536 15.51912,-2.93603 12.79281,-7.54986 z",

**Comment by neveldo** [comment]
Hello,

Thank for noticing it, but it seems that the "bois de Vincennes" area is part of the 12th district according to Google maps and other sources : https://www.google.fr/maps/place/12e+Arrondissement,+75012+Paris/@48.8291179,2.3638758,12z/data=!4m5!3m4!1s0x47e6728cb7d7d747:0x50b82c368941b00!8m2!3d48.8293647!4d2.4265406 , the same for the 16th district and the "bois de Boulogne" area : https://www.google.fr/maps/place/16e+Arrondissement,+Paris/@48.8570816,2.1228168,11z/data=!4m5!3m4!1s0x47e67ab3264355e9:0x50b82c368941b40!8m2!3d48.8585799!4d2.2847017

**Comment by neveldo** [comment]
On wikimedia commons, both maps can be found including or excluding these two wood areas : 

https://commons.wikimedia.org/wiki/File:Paris_department_location_map.svg
https://commons.wikimedia.org/wiki/File:Numbered_map_of_Paris_with_Bois_de_Boulogne_and_Bois_de_Vincennes.svg

Maybe the proper solution should be to provide these two versions of the Mapael map of Paris.
