### ISSUE TITLE
onclick modal

### ISSUE THREAD

**Issue by moosaace** [neveldo/mapael-maps#28]
Hi,
I am trying this for a while and i am unable to get what i wanted so i kindly ask if anyone can assist me. 
Below is my code, i am trying to find a way to make a modal window pop up when i click the to country **NL**  right now its a href when you click it will open a new tab with the assigned link.

 // Customize some areas of the map
                areas: {
                    "department-56": {
                        text: {content: "Morbihan", attrs: {"font-size": 10}},
                        tooltip: {content: "Morbihan (56)"}
                    },
                        //netherland
                        "NL": {
                        attrs: {
                            fill: "#48B75F"
                        }
                        , attrsHover: {
                            fill: "#a4e100"
                        },
                        href: "http://fr.wikipedia.org/wiki/C%C3%B4te-d%27Or",
                        target: "_blank",
                             tooltip: {content: "Cinema NL"},
                    },

**Comment by neveldo** [comment]
Hi @moosaace , sorry for my late answer.

Did you check this example : https://rawgit.com/neveldo/jQuery-Mapael/master/examples/advanced/eventHandlers_display_information_about_plotted_cities.html ?

I think you just have to adapt the code of this example, by replacing the 'mouseover' event by a 'click' event in the eventHandlers section , and then, open your modal instead of displaying information in a div within the callback.

**Comment by moosaace** [comment]
Hey thank you for your reply, i couldn't build it so in the end i found another library and achieved what i wanted. below is the link just to show you the idea. do you think if i change 'mouseover' event by a 'click'  function it will do it? because in the example you show me i see they all update in to one single 'DIV'.

[](http://moosamail.com/map/)

**Comment by neveldo** [comment]
There is not modal feature within Mapael itself, you will also have to adapt the code within the handler that is triggered on click event. You are free to make whatever you want within it : you can build your own modal by using an additionnal jquery plugin (you can find tons of them by seaching 'jquery modal') or, for instance, by using the modal feature of twitter bootstrap : https://v4-alpha.getbootstrap.com/components/modal/ .

**Comment by OcaOcaD** [comment]
The example neveldo shares works pretty good. 

Look at the code below and notice that I got the link where I need to redirect in the "link" option on my plots. I'm pretty sure you can do the same with the areas.
$(".mapcontainer").mapael(
{
    "map": {
        "name" : "mexico",
        "zoom": {
            "enabled": true,
            "maxLevel": 10
        },
        defaultPlot:{
            size: 20,
            eventHandlers: {
                click: function (e, id, mapElem, textElem, elemOptions) {
                    if (typeof elemOptions.link != 'undefined') {
                        window.open( elemOptions.link );
                    }
                }
            }
        }
    },
...
"plots":{
        'Estadio Charros de Jalisco': {
            "latitude": 20.727766,
            "longitude": -103.381524,
            "link": "https://goo.gl/maps/HoTP8mk9fojamoEF6",
            tooltip: {content: "Estadio Charros de Jalisco"},
            value: "Value 1"
        },
...
}
